// Major cities by country code (top cities for each country)
// This is a simplified list - for production, consider using a geo API

export const citiesByCountry: Record<string, string[]> = {
  AF: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"],
  AL: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Elbasan"],
  DZ: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  AD: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria"],
  AO: ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango"],
  AG: ["St. John's"],
  AR: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata"],
  AM: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat"],
  AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Hobart", "Darwin"],
  AT: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt"],
  AZ: ["Baku", "Ganja", "Sumqayit", "Mingachevir"],
  BS: ["Nassau", "Freeport"],
  BH: ["Manama", "Riffa", "Muharraq"],
  BD: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  BB: ["Bridgetown"],
  BY: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno"],
  BE: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur"],
  BZ: ["Belize City", "San Ignacio", "Belmopan"],
  BJ: ["Cotonou", "Porto-Novo", "Parakou"],
  BT: ["Thimphu", "Paro", "Punakha"],
  BO: ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro"],
  BA: ["Sarajevo", "Banja Luka", "Mostar", "Tuzla", "Zenica"],
  BW: ["Gaborone", "Francistown", "Maun"],
  BR: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre"],
  BN: ["Bandar Seri Begawan"],
  BG: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  BF: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"],
  BI: ["Bujumbura", "Gitega", "Ngozi"],
  CV: ["Praia", "Mindelo"],
  KH: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
  CM: ["Yaoundé", "Douala", "Garoua", "Bamenda"],
  CA: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Victoria"],
  CF: ["Bangui"],
  TD: ["N'Djamena", "Moundou", "Sarh"],
  CL: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco"],
  CN: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen", "Chengdu", "Hangzhou", "Wuhan", "Xi'an", "Nanjing", "Chongqing", "Tianjin", "Hong Kong"],
  CO: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga"],
  KM: ["Moroni", "Mutsamudu"],
  CG: ["Brazzaville", "Pointe-Noire"],
  CD: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Kananga"],
  CR: ["San José", "Limón", "Alajuela", "Heredia"],
  CI: ["Abidjan", "Yamoussoukro", "Bouaké", "Daloa"],
  HR: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Dubrovnik"],
  CU: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín"],
  CY: ["Nicosia", "Limassol", "Larnaca", "Paphos"],
  CZ: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc"],
  DK: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Frederiksberg"],
  DJ: ["Djibouti"],
  DM: ["Roseau"],
  DO: ["Santo Domingo", "Santiago", "San Pedro de Macorís", "La Romana"],
  EC: ["Quito", "Guayaquil", "Cuenca", "Machala", "Manta"],
  EG: ["Cairo", "Alexandria", "Giza", "Sharm El Sheikh", "Luxor", "Aswan", "Port Said"],
  SV: ["San Salvador", "Santa Ana", "Soyapango"],
  GQ: ["Malabo", "Bata"],
  ER: ["Asmara", "Keren", "Massawa"],
  EE: ["Tallinn", "Tartu", "Narva", "Pärnu"],
  SZ: ["Mbabane", "Manzini"],
  ET: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Bahir Dar"],
  FJ: ["Suva", "Nadi", "Lautoka"],
  FI: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku"],
  FR: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Grenoble"],
  GA: ["Libreville", "Port-Gentil", "Franceville"],
  GM: ["Banjul", "Serekunda"],
  GE: ["Tbilisi", "Batumi", "Kutaisi", "Rustavi"],
  DE: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden"],
  GH: ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi"],
  GR: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos"],
  GD: ["St. George's"],
  GT: ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango"],
  GN: ["Conakry", "Nzérékoré", "Kankan"],
  GW: ["Bissau", "Bafatá"],
  GY: ["Georgetown", "Linden"],
  HT: ["Port-au-Prince", "Cap-Haïtien", "Gonaïves"],
  HN: ["Tegucigalpa", "San Pedro Sula", "La Ceiba"],
  HU: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Győr"],
  IS: ["Reykjavik", "Kópavogur", "Hafnarfjörður", "Akureyri"],
  IN: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Ahmedabad", "Pune", "Jaipur", "Lucknow", "Surat"],
  ID: ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Bali", "Yogyakarta", "Makassar"],
  IR: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz"],
  IQ: ["Baghdad", "Basra", "Mosul", "Erbil", "Kirkuk", "Najaf"],
  IE: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  IL: ["Tel Aviv", "Jerusalem", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod"],
  IT: ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Venice", "Verona", "Bari"],
  JM: ["Kingston", "Montego Bay", "Spanish Town"],
  JP: ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo", "Kobe", "Kyoto", "Fukuoka", "Kawasaki", "Hiroshima"],
  JO: ["Amman", "Zarqa", "Irbid", "Aqaba"],
  KZ: ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe"],
  KE: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  KI: ["Tarawa"],
  KP: ["Pyongyang", "Hamhung", "Chongjin", "Nampo"],
  KR: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan", "Suwon"],
  KW: ["Kuwait City", "Hawalli", "Salmiya"],
  KG: ["Bishkek", "Osh", "Jalal-Abad"],
  LA: ["Vientiane", "Luang Prabang", "Pakse"],
  LV: ["Riga", "Daugavpils", "Liepaja", "Jelgava"],
  LB: ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh"],
  LS: ["Maseru", "Teyateyaneng"],
  LR: ["Monrovia", "Gbarnga"],
  LY: ["Tripoli", "Benghazi", "Misrata"],
  LI: ["Vaduz", "Schaan"],
  LT: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai"],
  LU: ["Luxembourg City", "Esch-sur-Alzette", "Differdange"],
  MG: ["Antananarivo", "Toamasina", "Antsirabe"],
  MW: ["Lilongwe", "Blantyre", "Mzuzu"],
  MY: ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Shah Alam", "Malacca City"],
  MV: ["Malé"],
  ML: ["Bamako", "Sikasso", "Mopti", "Timbuktu"],
  MT: ["Valletta", "Birkirkara", "Sliema"],
  MH: ["Majuro"],
  MR: ["Nouakchott", "Nouadhibou"],
  MU: ["Port Louis", "Vacoas-Phoenix"],
  MX: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Ciudad Juárez", "Mérida", "Cancún", "Acapulco"],
  FM: ["Palikir", "Weno"],
  MD: ["Chișinău", "Tiraspol", "Bălți"],
  MC: ["Monaco"],
  MN: ["Ulaanbaatar", "Erdenet", "Darkhan"],
  ME: ["Podgorica", "Nikšić", "Herceg Novi", "Budva"],
  MA: ["Casablanca", "Rabat", "Marrakech", "Fes", "Tangier", "Agadir", "Meknes"],
  MZ: ["Maputo", "Matola", "Beira", "Nampula"],
  MM: ["Yangon", "Mandalay", "Naypyidaw", "Bago"],
  NA: ["Windhoek", "Walvis Bay", "Swakopmund"],
  NR: ["Yaren"],
  NP: ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"],
  NL: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen", "Tilburg", "Almere"],
  NZ: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin", "Queenstown"],
  NI: ["Managua", "León", "Masaya", "Matagalpa"],
  NE: ["Niamey", "Zinder", "Maradi"],
  NG: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Kaduna", "Benin City"],
  MK: ["Skopje", "Bitola", "Kumanovo", "Ohrid"],
  NO: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Tromsø"],
  OM: ["Muscat", "Salalah", "Sohar"],
  PK: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Islamabad", "Multan", "Peshawar"],
  PW: ["Ngerulmud"],
  PS: ["Gaza", "Ramallah", "Hebron", "Nablus", "Bethlehem"],
  PA: ["Panama City", "Colón", "David"],
  PG: ["Port Moresby", "Lae", "Mount Hagen"],
  PY: ["Asunción", "Ciudad del Este", "San Lorenzo"],
  PE: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Cusco", "Piura"],
  PH: ["Manila", "Quezon City", "Davao", "Cebu City", "Makati", "Zamboanga"],
  PL: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Lublin"],
  PT: ["Lisbon", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Funchal"],
  QA: ["Doha", "Al Rayyan", "Al Wakrah"],
  RO: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Brașov"],
  RU: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Nizhny Novgorod", "Kazan", "Samara", "Sochi", "Vladivostok"],
  RW: ["Kigali", "Butare", "Gisenyi"],
  KN: ["Basseterre"],
  LC: ["Castries"],
  VC: ["Kingstown"],
  WS: ["Apia"],
  SM: ["San Marino"],
  ST: ["São Tomé"],
  SA: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar"],
  SN: ["Dakar", "Touba", "Thiès", "Saint-Louis"],
  RS: ["Belgrade", "Novi Sad", "Niš", "Kragujevac"],
  SC: ["Victoria"],
  SL: ["Freetown", "Bo", "Kenema"],
  SG: ["Singapore"],
  SK: ["Bratislava", "Košice", "Prešov", "Nitra", "Žilina"],
  SI: ["Ljubljana", "Maribor", "Celje", "Kranj"],
  SB: ["Honiara"],
  SO: ["Mogadishu", "Hargeisa", "Berbera"],
  ZA: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein"],
  SS: ["Juba", "Malakal", "Wau"],
  ES: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Bilbao", "Granada"],
  LK: ["Colombo", "Sri Jayawardenepura Kotte", "Kandy", "Galle"],
  SD: ["Khartoum", "Omdurman", "Port Sudan"],
  SR: ["Paramaribo"],
  SE: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro"],
  CH: ["Zurich", "Geneva", "Basel", "Lausanne", "Bern", "Winterthur", "Lucerne"],
  SY: ["Damascus", "Aleppo", "Homs", "Latakia"],
  TW: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu"],
  TJ: ["Dushanbe", "Khujand", "Kulob"],
  TZ: ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Zanzibar City"],
  TH: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Nonthaburi", "Hat Yai"],
  TL: ["Dili", "Baucau"],
  TG: ["Lomé", "Sokodé", "Kara"],
  TO: ["Nukuʻalofa"],
  TT: ["Port of Spain", "Chaguanas", "San Fernando"],
  TN: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
  TR: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep", "Konya"],
  TM: ["Ashgabat", "Türkmenabat", "Daşoguz"],
  TV: ["Funafuti"],
  UG: ["Kampala", "Gulu", "Lira", "Mbarara"],
  UA: ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv", "Zaporizhzhia"],
  AE: ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah"],
  GB: ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Leeds", "Bristol", "Sheffield", "Edinburgh", "Cardiff", "Belfast"],
  US: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Miami", "Seattle", "Denver", "Boston", "Las Vegas", "San Francisco", "Washington D.C."],
  UY: ["Montevideo", "Salto", "Paysandú", "Las Piedras"],
  UZ: ["Tashkent", "Samarkand", "Bukhara", "Namangan", "Andijan"],
  VU: ["Port Vila", "Luganville"],
  VA: ["Vatican City"],
  VE: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
  VN: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Nha Trang"],
  YE: ["Sana'a", "Aden", "Taiz", "Al Hudaydah"],
  ZM: ["Lusaka", "Kitwe", "Ndola", "Kabwe"],
  ZW: ["Harare", "Bulawayo", "Chitungwiza", "Mutare"],
};

export function getCitiesForCountry(countryCode: string): string[] {
  return citiesByCountry[countryCode] || [];
}
