// ISO 3166-1 alpha-2 country codes with translations
export interface Country {
  code: string;
  names: {
    en: string;
    fr: string;
    es: string;
    ko: string;
    zh: string;
  };
}

export const countries: Country[] = [
  { code: "AF", names: { en: "Afghanistan", fr: "Afghanistan", es: "Afganistán", ko: "아프가니스탄", zh: "阿富汗" } },
  { code: "AL", names: { en: "Albania", fr: "Albanie", es: "Albania", ko: "알바니아", zh: "阿尔巴尼亚" } },
  { code: "DZ", names: { en: "Algeria", fr: "Algérie", es: "Argelia", ko: "알제리", zh: "阿尔及利亚" } },
  { code: "AD", names: { en: "Andorra", fr: "Andorre", es: "Andorra", ko: "안도라", zh: "安道尔" } },
  { code: "AO", names: { en: "Angola", fr: "Angola", es: "Angola", ko: "앙골라", zh: "安哥拉" } },
  { code: "AG", names: { en: "Antigua and Barbuda", fr: "Antigua-et-Barbuda", es: "Antigua y Barbuda", ko: "앤티가 바부다", zh: "安提瓜和巴布达" } },
  { code: "AR", names: { en: "Argentina", fr: "Argentine", es: "Argentina", ko: "아르헨티나", zh: "阿根廷" } },
  { code: "AM", names: { en: "Armenia", fr: "Arménie", es: "Armenia", ko: "아르메니아", zh: "亚美尼亚" } },
  { code: "AU", names: { en: "Australia", fr: "Australie", es: "Australia", ko: "호주", zh: "澳大利亚" } },
  { code: "AT", names: { en: "Austria", fr: "Autriche", es: "Austria", ko: "오스트리아", zh: "奥地利" } },
  { code: "AZ", names: { en: "Azerbaijan", fr: "Azerbaïdjan", es: "Azerbaiyán", ko: "아제르바이잔", zh: "阿塞拜疆" } },
  { code: "BS", names: { en: "Bahamas", fr: "Bahamas", es: "Bahamas", ko: "바하마", zh: "巴哈马" } },
  { code: "BH", names: { en: "Bahrain", fr: "Bahreïn", es: "Baréin", ko: "바레인", zh: "巴林" } },
  { code: "BD", names: { en: "Bangladesh", fr: "Bangladesh", es: "Bangladés", ko: "방글라데시", zh: "孟加拉国" } },
  { code: "BB", names: { en: "Barbados", fr: "Barbade", es: "Barbados", ko: "바베이도스", zh: "巴巴多斯" } },
  { code: "BY", names: { en: "Belarus", fr: "Biélorussie", es: "Bielorrusia", ko: "벨라루스", zh: "白俄罗斯" } },
  { code: "BE", names: { en: "Belgium", fr: "Belgique", es: "Bélgica", ko: "벨기에", zh: "比利时" } },
  { code: "BZ", names: { en: "Belize", fr: "Belize", es: "Belice", ko: "벨리즈", zh: "伯利兹" } },
  { code: "BJ", names: { en: "Benin", fr: "Bénin", es: "Benín", ko: "베냉", zh: "贝宁" } },
  { code: "BT", names: { en: "Bhutan", fr: "Bhoutan", es: "Bután", ko: "부탄", zh: "不丹" } },
  { code: "BO", names: { en: "Bolivia", fr: "Bolivie", es: "Bolivia", ko: "볼리비아", zh: "玻利维亚" } },
  { code: "BA", names: { en: "Bosnia and Herzegovina", fr: "Bosnie-Herzégovine", es: "Bosnia y Herzegovina", ko: "보스니아 헤르체고비나", zh: "波斯尼亚和黑塞哥维那" } },
  { code: "BW", names: { en: "Botswana", fr: "Botswana", es: "Botsuana", ko: "보츠와나", zh: "博茨瓦纳" } },
  { code: "BR", names: { en: "Brazil", fr: "Brésil", es: "Brasil", ko: "브라질", zh: "巴西" } },
  { code: "BN", names: { en: "Brunei", fr: "Brunei", es: "Brunéi", ko: "브루나이", zh: "文莱" } },
  { code: "BG", names: { en: "Bulgaria", fr: "Bulgarie", es: "Bulgaria", ko: "불가리아", zh: "保加利亚" } },
  { code: "BF", names: { en: "Burkina Faso", fr: "Burkina Faso", es: "Burkina Faso", ko: "부르키나파소", zh: "布基纳法索" } },
  { code: "BI", names: { en: "Burundi", fr: "Burundi", es: "Burundi", ko: "부룬디", zh: "布隆迪" } },
  { code: "CV", names: { en: "Cabo Verde", fr: "Cap-Vert", es: "Cabo Verde", ko: "카보베르데", zh: "佛得角" } },
  { code: "KH", names: { en: "Cambodia", fr: "Cambodge", es: "Camboya", ko: "캄보디아", zh: "柬埔寨" } },
  { code: "CM", names: { en: "Cameroon", fr: "Cameroun", es: "Camerún", ko: "카메룬", zh: "喀麦隆" } },
  { code: "CA", names: { en: "Canada", fr: "Canada", es: "Canadá", ko: "캐나다", zh: "加拿大" } },
  { code: "CF", names: { en: "Central African Republic", fr: "République centrafricaine", es: "República Centroafricana", ko: "중앙아프리카공화국", zh: "中非共和国" } },
  { code: "TD", names: { en: "Chad", fr: "Tchad", es: "Chad", ko: "차드", zh: "乍得" } },
  { code: "CL", names: { en: "Chile", fr: "Chili", es: "Chile", ko: "칠레", zh: "智利" } },
  { code: "CN", names: { en: "China", fr: "Chine", es: "China", ko: "중국", zh: "中国" } },
  { code: "CO", names: { en: "Colombia", fr: "Colombie", es: "Colombia", ko: "콜롬비아", zh: "哥伦比亚" } },
  { code: "KM", names: { en: "Comoros", fr: "Comores", es: "Comoras", ko: "코모로", zh: "科摩罗" } },
  { code: "CG", names: { en: "Congo", fr: "Congo", es: "Congo", ko: "콩고", zh: "刚果" } },
  { code: "CD", names: { en: "DR Congo", fr: "RD Congo", es: "RD Congo", ko: "콩고민주공화국", zh: "刚果民主共和国" } },
  { code: "CR", names: { en: "Costa Rica", fr: "Costa Rica", es: "Costa Rica", ko: "코스타리카", zh: "哥斯达黎加" } },
  { code: "CI", names: { en: "Côte d'Ivoire", fr: "Côte d'Ivoire", es: "Costa de Marfil", ko: "코트디부아르", zh: "科特迪瓦" } },
  { code: "HR", names: { en: "Croatia", fr: "Croatie", es: "Croacia", ko: "크로아티아", zh: "克罗地亚" } },
  { code: "CU", names: { en: "Cuba", fr: "Cuba", es: "Cuba", ko: "쿠바", zh: "古巴" } },
  { code: "CY", names: { en: "Cyprus", fr: "Chypre", es: "Chipre", ko: "키프로스", zh: "塞浦路斯" } },
  { code: "CZ", names: { en: "Czech Republic", fr: "République tchèque", es: "República Checa", ko: "체코", zh: "捷克" } },
  { code: "DK", names: { en: "Denmark", fr: "Danemark", es: "Dinamarca", ko: "덴마크", zh: "丹麦" } },
  { code: "DJ", names: { en: "Djibouti", fr: "Djibouti", es: "Yibuti", ko: "지부티", zh: "吉布提" } },
  { code: "DM", names: { en: "Dominica", fr: "Dominique", es: "Dominica", ko: "도미니카", zh: "多米尼克" } },
  { code: "DO", names: { en: "Dominican Republic", fr: "République dominicaine", es: "República Dominicana", ko: "도미니카공화국", zh: "多米尼加共和国" } },
  { code: "EC", names: { en: "Ecuador", fr: "Équateur", es: "Ecuador", ko: "에콰도르", zh: "厄瓜多尔" } },
  { code: "EG", names: { en: "Egypt", fr: "Égypte", es: "Egipto", ko: "이집트", zh: "埃及" } },
  { code: "SV", names: { en: "El Salvador", fr: "Salvador", es: "El Salvador", ko: "엘살바도르", zh: "萨尔瓦多" } },
  { code: "GQ", names: { en: "Equatorial Guinea", fr: "Guinée équatoriale", es: "Guinea Ecuatorial", ko: "적도기니", zh: "赤道几内亚" } },
  { code: "ER", names: { en: "Eritrea", fr: "Érythrée", es: "Eritrea", ko: "에리트레아", zh: "厄立特里亚" } },
  { code: "EE", names: { en: "Estonia", fr: "Estonie", es: "Estonia", ko: "에스토니아", zh: "爱沙尼亚" } },
  { code: "SZ", names: { en: "Eswatini", fr: "Eswatini", es: "Esuatini", ko: "에스와티니", zh: "斯威士兰" } },
  { code: "ET", names: { en: "Ethiopia", fr: "Éthiopie", es: "Etiopía", ko: "에티오피아", zh: "埃塞俄比亚" } },
  { code: "FJ", names: { en: "Fiji", fr: "Fidji", es: "Fiyi", ko: "피지", zh: "斐济" } },
  { code: "FI", names: { en: "Finland", fr: "Finlande", es: "Finlandia", ko: "핀란드", zh: "芬兰" } },
  { code: "FR", names: { en: "France", fr: "France", es: "Francia", ko: "프랑스", zh: "法国" } },
  { code: "GA", names: { en: "Gabon", fr: "Gabon", es: "Gabón", ko: "가봉", zh: "加蓬" } },
  { code: "GM", names: { en: "Gambia", fr: "Gambie", es: "Gambia", ko: "감비아", zh: "冈比亚" } },
  { code: "GE", names: { en: "Georgia", fr: "Géorgie", es: "Georgia", ko: "조지아", zh: "格鲁吉亚" } },
  { code: "DE", names: { en: "Germany", fr: "Allemagne", es: "Alemania", ko: "독일", zh: "德国" } },
  { code: "GH", names: { en: "Ghana", fr: "Ghana", es: "Ghana", ko: "가나", zh: "加纳" } },
  { code: "GR", names: { en: "Greece", fr: "Grèce", es: "Grecia", ko: "그리스", zh: "希腊" } },
  { code: "GD", names: { en: "Grenada", fr: "Grenade", es: "Granada", ko: "그레나다", zh: "格林纳达" } },
  { code: "GT", names: { en: "Guatemala", fr: "Guatemala", es: "Guatemala", ko: "과테말라", zh: "危地马拉" } },
  { code: "GN", names: { en: "Guinea", fr: "Guinée", es: "Guinea", ko: "기니", zh: "几内亚" } },
  { code: "GW", names: { en: "Guinea-Bissau", fr: "Guinée-Bissau", es: "Guinea-Bisáu", ko: "기니비사우", zh: "几内亚比绍" } },
  { code: "GY", names: { en: "Guyana", fr: "Guyana", es: "Guyana", ko: "가이아나", zh: "圭亚那" } },
  { code: "HT", names: { en: "Haiti", fr: "Haïti", es: "Haití", ko: "아이티", zh: "海地" } },
  { code: "HN", names: { en: "Honduras", fr: "Honduras", es: "Honduras", ko: "온두라스", zh: "洪都拉斯" } },
  { code: "HU", names: { en: "Hungary", fr: "Hongrie", es: "Hungría", ko: "헝가리", zh: "匈牙利" } },
  { code: "IS", names: { en: "Iceland", fr: "Islande", es: "Islandia", ko: "아이슬란드", zh: "冰岛" } },
  { code: "IN", names: { en: "India", fr: "Inde", es: "India", ko: "인도", zh: "印度" } },
  { code: "ID", names: { en: "Indonesia", fr: "Indonésie", es: "Indonesia", ko: "인도네시아", zh: "印度尼西亚" } },
  { code: "IR", names: { en: "Iran", fr: "Iran", es: "Irán", ko: "이란", zh: "伊朗" } },
  { code: "IQ", names: { en: "Iraq", fr: "Irak", es: "Irak", ko: "이라크", zh: "伊拉克" } },
  { code: "IE", names: { en: "Ireland", fr: "Irlande", es: "Irlanda", ko: "아일랜드", zh: "爱尔兰" } },
  { code: "IL", names: { en: "Israel", fr: "Israël", es: "Israel", ko: "이스라엘", zh: "以色列" } },
  { code: "IT", names: { en: "Italy", fr: "Italie", es: "Italia", ko: "이탈리아", zh: "意大利" } },
  { code: "JM", names: { en: "Jamaica", fr: "Jamaïque", es: "Jamaica", ko: "자메이카", zh: "牙买加" } },
  { code: "JP", names: { en: "Japan", fr: "Japon", es: "Japón", ko: "일본", zh: "日本" } },
  { code: "JO", names: { en: "Jordan", fr: "Jordanie", es: "Jordania", ko: "요르단", zh: "约旦" } },
  { code: "KZ", names: { en: "Kazakhstan", fr: "Kazakhstan", es: "Kazajistán", ko: "카자흐스탄", zh: "哈萨克斯坦" } },
  { code: "KE", names: { en: "Kenya", fr: "Kenya", es: "Kenia", ko: "케냐", zh: "肯尼亚" } },
  { code: "KI", names: { en: "Kiribati", fr: "Kiribati", es: "Kiribati", ko: "키리바시", zh: "基里巴斯" } },
  { code: "KP", names: { en: "North Korea", fr: "Corée du Nord", es: "Corea del Norte", ko: "북한", zh: "朝鲜" } },
  { code: "KR", names: { en: "South Korea", fr: "Corée du Sud", es: "Corea del Sur", ko: "대한민국", zh: "韩国" } },
  { code: "KW", names: { en: "Kuwait", fr: "Koweït", es: "Kuwait", ko: "쿠웨이트", zh: "科威特" } },
  { code: "KG", names: { en: "Kyrgyzstan", fr: "Kirghizistan", es: "Kirguistán", ko: "키르기스스탄", zh: "吉尔吉斯斯坦" } },
  { code: "LA", names: { en: "Laos", fr: "Laos", es: "Laos", ko: "라오스", zh: "老挝" } },
  { code: "LV", names: { en: "Latvia", fr: "Lettonie", es: "Letonia", ko: "라트비아", zh: "拉脱维亚" } },
  { code: "LB", names: { en: "Lebanon", fr: "Liban", es: "Líbano", ko: "레바논", zh: "黎巴嫩" } },
  { code: "LS", names: { en: "Lesotho", fr: "Lesotho", es: "Lesoto", ko: "레소토", zh: "莱索托" } },
  { code: "LR", names: { en: "Liberia", fr: "Liberia", es: "Liberia", ko: "라이베리아", zh: "利比里亚" } },
  { code: "LY", names: { en: "Libya", fr: "Libye", es: "Libia", ko: "리비아", zh: "利比亚" } },
  { code: "LI", names: { en: "Liechtenstein", fr: "Liechtenstein", es: "Liechtenstein", ko: "리히텐슈타인", zh: "列支敦士登" } },
  { code: "LT", names: { en: "Lithuania", fr: "Lituanie", es: "Lituania", ko: "리투아니아", zh: "立陶宛" } },
  { code: "LU", names: { en: "Luxembourg", fr: "Luxembourg", es: "Luxemburgo", ko: "룩셈부르크", zh: "卢森堡" } },
  { code: "MG", names: { en: "Madagascar", fr: "Madagascar", es: "Madagascar", ko: "마다가스카르", zh: "马达加斯加" } },
  { code: "MW", names: { en: "Malawi", fr: "Malawi", es: "Malaui", ko: "말라위", zh: "马拉维" } },
  { code: "MY", names: { en: "Malaysia", fr: "Malaisie", es: "Malasia", ko: "말레이시아", zh: "马来西亚" } },
  { code: "MV", names: { en: "Maldives", fr: "Maldives", es: "Maldivas", ko: "몰디브", zh: "马尔代夫" } },
  { code: "ML", names: { en: "Mali", fr: "Mali", es: "Malí", ko: "말리", zh: "马里" } },
  { code: "MT", names: { en: "Malta", fr: "Malte", es: "Malta", ko: "몰타", zh: "马耳他" } },
  { code: "MH", names: { en: "Marshall Islands", fr: "Îles Marshall", es: "Islas Marshall", ko: "마셜 제도", zh: "马绍尔群岛" } },
  { code: "MR", names: { en: "Mauritania", fr: "Mauritanie", es: "Mauritania", ko: "모리타니", zh: "毛里塔尼亚" } },
  { code: "MU", names: { en: "Mauritius", fr: "Maurice", es: "Mauricio", ko: "모리셔스", zh: "毛里求斯" } },
  { code: "MX", names: { en: "Mexico", fr: "Mexique", es: "México", ko: "멕시코", zh: "墨西哥" } },
  { code: "FM", names: { en: "Micronesia", fr: "Micronésie", es: "Micronesia", ko: "미크로네시아", zh: "密克罗尼西亚" } },
  { code: "MD", names: { en: "Moldova", fr: "Moldavie", es: "Moldavia", ko: "몰도바", zh: "摩尔多瓦" } },
  { code: "MC", names: { en: "Monaco", fr: "Monaco", es: "Mónaco", ko: "모나코", zh: "摩纳哥" } },
  { code: "MN", names: { en: "Mongolia", fr: "Mongolie", es: "Mongolia", ko: "몽골", zh: "蒙古" } },
  { code: "ME", names: { en: "Montenegro", fr: "Monténégro", es: "Montenegro", ko: "몬테네그로", zh: "黑山" } },
  { code: "MA", names: { en: "Morocco", fr: "Maroc", es: "Marruecos", ko: "모로코", zh: "摩洛哥" } },
  { code: "MZ", names: { en: "Mozambique", fr: "Mozambique", es: "Mozambique", ko: "모잠비크", zh: "莫桑比克" } },
  { code: "MM", names: { en: "Myanmar", fr: "Myanmar", es: "Myanmar", ko: "미얀마", zh: "缅甸" } },
  { code: "NA", names: { en: "Namibia", fr: "Namibie", es: "Namibia", ko: "나미비아", zh: "纳米比亚" } },
  { code: "NR", names: { en: "Nauru", fr: "Nauru", es: "Nauru", ko: "나우루", zh: "瑙鲁" } },
  { code: "NP", names: { en: "Nepal", fr: "Népal", es: "Nepal", ko: "네팔", zh: "尼泊尔" } },
  { code: "NL", names: { en: "Netherlands", fr: "Pays-Bas", es: "Países Bajos", ko: "네덜란드", zh: "荷兰" } },
  { code: "NZ", names: { en: "New Zealand", fr: "Nouvelle-Zélande", es: "Nueva Zelanda", ko: "뉴질랜드", zh: "新西兰" } },
  { code: "NI", names: { en: "Nicaragua", fr: "Nicaragua", es: "Nicaragua", ko: "니카라과", zh: "尼加拉瓜" } },
  { code: "NE", names: { en: "Niger", fr: "Niger", es: "Níger", ko: "니제르", zh: "尼日尔" } },
  { code: "NG", names: { en: "Nigeria", fr: "Nigeria", es: "Nigeria", ko: "나이지리아", zh: "尼日利亚" } },
  { code: "MK", names: { en: "North Macedonia", fr: "Macédoine du Nord", es: "Macedonia del Norte", ko: "북마케도니아", zh: "北马其顿" } },
  { code: "NO", names: { en: "Norway", fr: "Norvège", es: "Noruega", ko: "노르웨이", zh: "挪威" } },
  { code: "OM", names: { en: "Oman", fr: "Oman", es: "Omán", ko: "오만", zh: "阿曼" } },
  { code: "PK", names: { en: "Pakistan", fr: "Pakistan", es: "Pakistán", ko: "파키스탄", zh: "巴基斯坦" } },
  { code: "PW", names: { en: "Palau", fr: "Palaos", es: "Palaos", ko: "팔라우", zh: "帕劳" } },
  { code: "PS", names: { en: "Palestine", fr: "Palestine", es: "Palestina", ko: "팔레스타인", zh: "巴勒斯坦" } },
  { code: "PA", names: { en: "Panama", fr: "Panama", es: "Panamá", ko: "파나마", zh: "巴拿马" } },
  { code: "PG", names: { en: "Papua New Guinea", fr: "Papouasie-Nouvelle-Guinée", es: "Papúa Nueva Guinea", ko: "파푸아뉴기니", zh: "巴布亚新几内亚" } },
  { code: "PY", names: { en: "Paraguay", fr: "Paraguay", es: "Paraguay", ko: "파라과이", zh: "巴拉圭" } },
  { code: "PE", names: { en: "Peru", fr: "Pérou", es: "Perú", ko: "페루", zh: "秘鲁" } },
  { code: "PH", names: { en: "Philippines", fr: "Philippines", es: "Filipinas", ko: "필리핀", zh: "菲律宾" } },
  { code: "PL", names: { en: "Poland", fr: "Pologne", es: "Polonia", ko: "폴란드", zh: "波兰" } },
  { code: "PT", names: { en: "Portugal", fr: "Portugal", es: "Portugal", ko: "포르투갈", zh: "葡萄牙" } },
  { code: "QA", names: { en: "Qatar", fr: "Qatar", es: "Catar", ko: "카타르", zh: "卡塔尔" } },
  { code: "RO", names: { en: "Romania", fr: "Roumanie", es: "Rumania", ko: "루마니아", zh: "罗马尼亚" } },
  { code: "RU", names: { en: "Russia", fr: "Russie", es: "Rusia", ko: "러시아", zh: "俄罗斯" } },
  { code: "RW", names: { en: "Rwanda", fr: "Rwanda", es: "Ruanda", ko: "르완다", zh: "卢旺达" } },
  { code: "KN", names: { en: "Saint Kitts and Nevis", fr: "Saint-Kitts-et-Nevis", es: "San Cristóbal y Nieves", ko: "세인트키츠 네비스", zh: "圣基茨和尼维斯" } },
  { code: "LC", names: { en: "Saint Lucia", fr: "Sainte-Lucie", es: "Santa Lucía", ko: "세인트루시아", zh: "圣卢西亚" } },
  { code: "VC", names: { en: "Saint Vincent and the Grenadines", fr: "Saint-Vincent-et-les-Grenadines", es: "San Vicente y las Granadinas", ko: "세인트빈센트 그레나딘", zh: "圣文森特和格林纳丁斯" } },
  { code: "WS", names: { en: "Samoa", fr: "Samoa", es: "Samoa", ko: "사모아", zh: "萨摩亚" } },
  { code: "SM", names: { en: "San Marino", fr: "Saint-Marin", es: "San Marino", ko: "산마리노", zh: "圣马力诺" } },
  { code: "ST", names: { en: "São Tomé and Príncipe", fr: "Sao Tomé-et-Príncipe", es: "Santo Tomé y Príncipe", ko: "상투메 프린시페", zh: "圣多美和普林西比" } },
  { code: "SA", names: { en: "Saudi Arabia", fr: "Arabie saoudite", es: "Arabia Saudita", ko: "사우디아라비아", zh: "沙特阿拉伯" } },
  { code: "SN", names: { en: "Senegal", fr: "Sénégal", es: "Senegal", ko: "세네갈", zh: "塞内加尔" } },
  { code: "RS", names: { en: "Serbia", fr: "Serbie", es: "Serbia", ko: "세르비아", zh: "塞尔维亚" } },
  { code: "SC", names: { en: "Seychelles", fr: "Seychelles", es: "Seychelles", ko: "세이셸", zh: "塞舌尔" } },
  { code: "SL", names: { en: "Sierra Leone", fr: "Sierra Leone", es: "Sierra Leona", ko: "시에라리온", zh: "塞拉利昂" } },
  { code: "SG", names: { en: "Singapore", fr: "Singapour", es: "Singapur", ko: "싱가포르", zh: "新加坡" } },
  { code: "SK", names: { en: "Slovakia", fr: "Slovaquie", es: "Eslovaquia", ko: "슬로바키아", zh: "斯洛伐克" } },
  { code: "SI", names: { en: "Slovenia", fr: "Slovénie", es: "Eslovenia", ko: "슬로베니아", zh: "斯洛文尼亚" } },
  { code: "SB", names: { en: "Solomon Islands", fr: "Îles Salomon", es: "Islas Salomón", ko: "솔로몬 제도", zh: "所罗门群岛" } },
  { code: "SO", names: { en: "Somalia", fr: "Somalie", es: "Somalia", ko: "소말리아", zh: "索马里" } },
  { code: "ZA", names: { en: "South Africa", fr: "Afrique du Sud", es: "Sudáfrica", ko: "남아프리카공화국", zh: "南非" } },
  { code: "SS", names: { en: "South Sudan", fr: "Soudan du Sud", es: "Sudán del Sur", ko: "남수단", zh: "南苏丹" } },
  { code: "ES", names: { en: "Spain", fr: "Espagne", es: "España", ko: "스페인", zh: "西班牙" } },
  { code: "LK", names: { en: "Sri Lanka", fr: "Sri Lanka", es: "Sri Lanka", ko: "스리랑카", zh: "斯里兰卡" } },
  { code: "SD", names: { en: "Sudan", fr: "Soudan", es: "Sudán", ko: "수단", zh: "苏丹" } },
  { code: "SR", names: { en: "Suriname", fr: "Suriname", es: "Surinam", ko: "수리남", zh: "苏里南" } },
  { code: "SE", names: { en: "Sweden", fr: "Suède", es: "Suecia", ko: "스웨덴", zh: "瑞典" } },
  { code: "CH", names: { en: "Switzerland", fr: "Suisse", es: "Suiza", ko: "스위스", zh: "瑞士" } },
  { code: "SY", names: { en: "Syria", fr: "Syrie", es: "Siria", ko: "시리아", zh: "叙利亚" } },
  { code: "TW", names: { en: "Taiwan", fr: "Taïwan", es: "Taiwán", ko: "대만", zh: "台湾" } },
  { code: "TJ", names: { en: "Tajikistan", fr: "Tadjikistan", es: "Tayikistán", ko: "타지키스탄", zh: "塔吉克斯坦" } },
  { code: "TZ", names: { en: "Tanzania", fr: "Tanzanie", es: "Tanzania", ko: "탄자니아", zh: "坦桑尼亚" } },
  { code: "TH", names: { en: "Thailand", fr: "Thaïlande", es: "Tailandia", ko: "태국", zh: "泰国" } },
  { code: "TL", names: { en: "Timor-Leste", fr: "Timor oriental", es: "Timor Oriental", ko: "동티모르", zh: "东帝汶" } },
  { code: "TG", names: { en: "Togo", fr: "Togo", es: "Togo", ko: "토고", zh: "多哥" } },
  { code: "TO", names: { en: "Tonga", fr: "Tonga", es: "Tonga", ko: "통가", zh: "汤加" } },
  { code: "TT", names: { en: "Trinidad and Tobago", fr: "Trinité-et-Tobago", es: "Trinidad y Tobago", ko: "트리니다드 토바고", zh: "特立尼达和多巴哥" } },
  { code: "TN", names: { en: "Tunisia", fr: "Tunisie", es: "Túnez", ko: "튀니지", zh: "突尼斯" } },
  { code: "TR", names: { en: "Turkey", fr: "Turquie", es: "Turquía", ko: "터키", zh: "土耳其" } },
  { code: "TM", names: { en: "Turkmenistan", fr: "Turkménistan", es: "Turkmenistán", ko: "투르크메니스탄", zh: "土库曼斯坦" } },
  { code: "TV", names: { en: "Tuvalu", fr: "Tuvalu", es: "Tuvalu", ko: "투발루", zh: "图瓦卢" } },
  { code: "UG", names: { en: "Uganda", fr: "Ouganda", es: "Uganda", ko: "우간다", zh: "乌干达" } },
  { code: "UA", names: { en: "Ukraine", fr: "Ukraine", es: "Ucrania", ko: "우크라이나", zh: "乌克兰" } },
  { code: "AE", names: { en: "United Arab Emirates", fr: "Émirats arabes unis", es: "Emiratos Árabes Unidos", ko: "아랍에미리트", zh: "阿联酋" } },
  { code: "GB", names: { en: "United Kingdom", fr: "Royaume-Uni", es: "Reino Unido", ko: "영국", zh: "英国" } },
  { code: "US", names: { en: "United States", fr: "États-Unis", es: "Estados Unidos", ko: "미국", zh: "美国" } },
  { code: "UY", names: { en: "Uruguay", fr: "Uruguay", es: "Uruguay", ko: "우루과이", zh: "乌拉圭" } },
  { code: "UZ", names: { en: "Uzbekistan", fr: "Ouzbékistan", es: "Uzbekistán", ko: "우즈베키스탄", zh: "乌兹别克斯坦" } },
  { code: "VU", names: { en: "Vanuatu", fr: "Vanuatu", es: "Vanuatu", ko: "바누아투", zh: "瓦努阿图" } },
  { code: "VA", names: { en: "Vatican City", fr: "Vatican", es: "Vaticano", ko: "바티칸", zh: "梵蒂冈" } },
  { code: "VE", names: { en: "Venezuela", fr: "Venezuela", es: "Venezuela", ko: "베네수엘라", zh: "委内瑞拉" } },
  { code: "VN", names: { en: "Vietnam", fr: "Vietnam", es: "Vietnam", ko: "베트남", zh: "越南" } },
  { code: "YE", names: { en: "Yemen", fr: "Yémen", es: "Yemen", ko: "예멘", zh: "也门" } },
  { code: "ZM", names: { en: "Zambia", fr: "Zambie", es: "Zambia", ko: "잠비아", zh: "赞比亚" } },
  { code: "ZW", names: { en: "Zimbabwe", fr: "Zimbabwe", es: "Zimbabue", ko: "짐바브웨", zh: "津巴布韦" } },
];

export function getCountryName(code: string, language: string): string {
  const country = countries.find(c => c.code === code);
  if (!country) return code;
  
  const lang = language as keyof Country['names'];
  return country.names[lang] || country.names.en;
}

export function getCountriesForLanguage(language: string): { code: string; name: string }[] {
  const lang = language as keyof Country['names'];
  return countries
    .map(c => ({
      code: c.code,
      name: c.names[lang] || c.names.en,
    }))
    .sort((a, b) => a.name.localeCompare(b.name, language));
}
